### ISSUE TITLE
EditColorActivity: submitting invalid text inputs (out of range or blank values) to the HSV/RGB sliders cause the app to crash.

### ISSUE THREAD

**Issue by PaigeRiola** [TheBrows/LiveColor#34]
- [ ] Edit Color user text inputs to either H, S, V, R, G, or B, will cause the app to crash if not within the proper range required for said value.
- Location: EditColorsActivity
- Possible action for removal: Either hitting the confirm button should check the value and not exit if incorrect, or the textbox is listened to as changed and prevents confirming if value is incorrect.
- [x] Edit Color blank user text inputs will cause the app to crash.
- Location: EditColorsActivity
- Possible action for removal: The new value should not be taken if blank, and nothing should happen to the original value.

**Comment by DustinSeltz** [comment]
Fixed the blank text crash. 
I'm not able to reproduce crashing on too large of an input.
