### ISSUE TITLE
ColorInfoActivity UI fixes

### ISSUE THREAD

**Issue by PaigeRiola** [TheBrows/LiveColor#39]
- [x] Left (Back button) and right (Edit button) buttons on top action bar should have the same padding
- [x] Center save button on top action bar, or place it directly to the left of the edit button on the action bar (with appropriate padding)
- [x] Adjust HEX, RGB, and HSV font sizes for readability and consistency. May require replacing the copy button contents with a clipboard icon to create more space for the HSV text.
- [x] View Color Harmonies button needs proper top and bottom margins. Might require making the info box taller, or removing the left, right, and bottom margins.
- [x] Improve Copy Icons in ColorInfoActivity
 - Clipboard 
 - little too big

**Comment by DanielLuft-Martinez** [comment]
those buttons already have the same padding, and no margin.
Perhaps icons are of different size/shape making the buttons look different

**Comment by DanielLuft-Martinez** [comment]
Ill try a version with the icon copy buttons

**Comment by DanielLuft-Martinez** [comment]
I've gone a couple different ways with the harmonies button, we'll see how the most recent push looks, but I have my doubts

**Comment by DanielLuft-Martinez** [comment]
not sure how I feel about the icon buttons, thoughts?

![image](https://user-images.githubusercontent.com/9016420/89940366-3d839180-dbce-11ea-8d05-8e28750918d9.png)

**Comment by DustinSeltz** [comment]
I feel like the text buttons were more clear than these icons.

**Comment by DanielLuft-Martinez** [comment]
I thinks so too, but if we can get good conveyance, then the icons will save us enough space for a larger font size for the values

**Comment by DanielLuft-Martinez** [comment]
left back padding changed to _look similar_ not be the same
