### ISSUE TITLE
EditColorActivity UI fixes

### ISSUE THREAD

**Issue by PaigeRiola** [TheBrows/LiveColor#40]
- [x] Back button left margin slightly too big.
- [x] RGB/HSV switch button needs right margin (should match fixed back button's left margin)
- [ ] Better indicator of edit-ability needed for the editable numeric values for RGB/HSV
- [x] Bottom Reset Color and Save New Color buttons need to be smaller and centered properly, along with their accompanying text.

**Comment by DanielLuft-Martinez** [comment]
I've made the bottom reset and save new color text and buttons smaller, but I dont see what you mean by centered properly?

![image](https://user-images.githubusercontent.com/9016420/89577181-26ffc380-d7e5-11ea-83e8-434cd6166d03.png)

**Comment by DanielLuft-Martinez** [comment]
I could try to see what underlining only the numbers looks like
