### ISSUE TITLE
SavedColorsFragment UI fixes

### ISSUE THREAD

**Issue by PaigeRiola** [TheBrows/LiveColor#42]
- [x] Adjust colors of the top bar buttons (List and Grid buttons) for readability and consistency. Should use the same accent color as the rest of the app. 
  - Solution: change the color of the image asset for the selected button icon to white so the tint can be changed programmatically.
- [x] Make background more recognizably apparent? in darkmode
- [x] more instagrammy icons

**Comment by DanielLuft-Martinez** [comment]
![image](https://user-images.githubusercontent.com/9016420/91501751-2e157100-e87b-11ea-8f1e-e9813cb07bf0.png)
![image](https://user-images.githubusercontent.com/9016420/91501766-38d00600-e87b-11ea-8de1-8f65410e1da0.png)
cards look like backgground, make buttons take up all of top areah

**Comment by DanielLuft-Martinez** [comment]
![savegdcolor newlooklist](https://user-images.githubusercontent.com/9016420/91904338-9ab4b500-ec59-11ea-8a4f-543afeac57b0.PNG)
![savegdcolor newlookgrid](https://user-images.githubusercontent.com/9016420/91904340-9be5e200-ec59-11ea-85a9-9ddb0413ec8c.PNG)

hows this for a little face lift
