### ISSUE TITLE
SettingsActivity UI fixes

### ISSUE THREAD

**Issue by PaigeRiola** [TheBrows/LiveColor#44]
- [x] Fix top and bottom padding on Settings header to be even.
- [x] Remove gap between settings and credits links that causes scrolling
- [x] Make the credits links more easily readable as buttons
- [x] Change settings to not be cards, try for cleaner look 
- [x] "Glow up" links at bottom of settings

**Comment by DanielLuft-Martinez** [comment]
How do we feel about underlined text as links?

![image](https://user-images.githubusercontent.com/9016420/89933252-a4e81400-dbc3-11ea-961a-bcd50f383b4e.png)

**Comment by tielm1997** [comment]
Looks okay to me.
