### ISSUE TITLE
Settings Feature: Allow user to chose between RGB/HSV as their color editing default

### ISSUE THREAD

**Issue by PaigeRiola** [TheBrows/LiveColor#83]
Option on SettingsActivity allowing the user to toggle between RGB and HSV as the default mode that the EditColorActivity appears on.

**Comment by DanielLuft-Martinez** [comment]
so, I dont think this needs its own setting, instead we can just save the state of the button as a pref and load it that way oncreate, like how we do with the saved colors list vs grid

**Comment by DanielLuft-Martinez** [comment]
played around with this a lot today, ended up scraping essentially everything
I think its still a solid strat, I just need to separate out a lot of features.
currently the state of the button changes a lot of things at different places in the lifecycle of the activity, 
as well as how the rest of the app interacts with it.
simply holding the value outside of the activity isnt gonna cut it, not without a fair amount of restructure.
The big issue that I manifested during testing, and why I ultimately pulled the plug on todays progress, 
is that depending on which mode the editor was in during onCreate/onResume and onDestroy/onPause
it was possible to have a single color with 4 separate names.
my testing revealed, that under the simple save edit mode state, 
color names were being generated in certain situations from a value assumed to be hex, but was actually hsv
switching back and forth while changing activity also cause some other issues, 
and yet another name could be generated when saving the color, even if sliders had not been touched.
for these reasons, I decided to pull out today, as I'd already completed at least a bit of work elsewhere.
perhaps a clearer head, and maybe some collaboration could solve the issues.

I suspect that I could fake it, by just forcing a click on the button, after its all been loaded, if the user left in hsv mode, though that didnt work when I first tried it.

**Comment by DanielLuft-Martinez** [comment]
![image](https://user-images.githubusercontent.com/9016420/93523893-91c61380-f8e8-11ea-97d0-e7ac6fac1062.png)

something fun I ran into

**Comment by DanielLuft-Martinez** [comment]
was actually able to fix it, all I had to do was call reset a couple times to clear saved values
I will be asking about it before merging to dev
![ezgif-6-e25e0e88b292](https://user-images.githubusercontent.com/9016420/93530384-5c262800-f8f2-11ea-876f-2195dd97b6ac.gif)
