### ISSUE TITLE
SettingsFragment: Use Android's Settings Activity template but as nested fragments

### ISSUE THREAD

**Issue by PaigeRiola** [TheBrows/LiveColor#92]
Android Settings Activity template provides a clean way to organize and navigate through all of the settings of your app (different navigable categories, titles and descriptions for each setting, etc.) It would also give us a better way to incorporate our credits into the settings fragment by giving it its own category.

![image](https://user-images.githubusercontent.com/43507693/91927340-116ba580-ec8e-11ea-9614-216681bb2fbf.png)

Would ideally have 3 different categories (as of now):
- General
- Appearance
- Color of the Day
- Credits

On the backlog because of the time it would take to implement, including setting it up as nested fragments instead of an activity and transferring the current settings features to new fragment(s)

- [x] Add back buttons to nested settings fragments

**Comment by DanielLuft-Martinez** [comment]
Its done, but could use extra testing/feedback

**Comment by DanielLuft-Martinez** [comment]
also need to add the new settings, and possibly scroll views eventually
